### ISSUE TITLE
[FEAT]: Automatically reset value to null /undefined

### ISSUE THREAD

**Issue by mtlalka** [tonysamperi/ngx-mat-timepicker#50] opened 2023-01-31 08:34 UTC
**Description**
I would expect a different behavior after clear time value. 

**Steps to reproduce the behavior:**
1. Open [Link to stackblitz](https://stackblitz.com/edit/angular-hjm5gw?file=src/main.ts)
2. Select any value, for example: 18:30 (ngModel value is 18:30)
3. Clear hour and minutes by backspace - ngModel value is 00:00 but time controls shows empty values (placeholder HH / MM is visible)

**Expected behavior**
ngModel value should be empty value (null or undefined or empty string)

**Comment by tonysamperi** [comment] 2023-02-03 19:00
Hi. Yes, this is reasonable, although the behaviour under the hood doesn't really allow to reset the control, because the only event emitted is about a time change. 
And because of how the input values are parsed, it will always basically return "00:00" when the inputs are empty.

The quite obvious workaround is having a reset button to allow the users to delete the value, instead of having them delete the inputs manually.
In the end this library is mainly focused on the picker, which you're not using in the example, so maybe for your use case you may want to use a different library. 
If I remember well ng-bootstrap has a time input which is more oriented to being a time input validator...

I'll see what can be done here, but it won't be quick unfortunately.

Cheers.

**Comment by tonysamperi** [comment] 2023-02-18 21:16
Hi @mtlalka 
I tried and wrote some lines to have this feature. 
The truth is that this can't be done without rethinking the entire thing.
Basically the problem is the way the original author used the NgxTimepickerService.
There you can't basically have empty values, because it validates against the possible values for the field control, plus it always falls back to the default time, which is 00:00.
The only thing I could do would be reset the input values to 00:00, but I guess that wouldn't solve.
I guess the workaround for you is simply forcing the user to disable the input instead of deleting the value.
I'll keep this in mind for the future implementation that I have in mind to do which will be inspired by these
https://material-ui-pickers.dev/demo/datetime-picker

**Closed by tonysamperi** 2023-02-18 21:16 UTC
Labels: enhancement, invalid, wontfix, fix: workaround
