### ISSUE TITLE
[BUG] - Wrong time in dialog after selection

### ISSUE THREAD

**Issue by SkyTien** [tonysamperi/ngx-mat-timepicker#29] opened 2022-04-27 04:29 UTC
**Describe the bug**
With "appendToInput" attribute is true, after click 'OK' in the picker dialog, the time is correct shown on the input, but not in the picker if you open picker again.

**To Reproduce**
It's also happened in your demo site 'Append to input' block.

**Expected behavior**
The select time should be correct in picker as well.

**Screenshots**
![Screen Shot 2022-04-27 at 12 26 51](https://user-images.githubusercontent.com/8827278/165440784-d52868db-f4bf-48e0-8cc6-12b83a0ebb5a.png)

**Desktop (if execution):**
 - OS: Mac
 - Browser chrome

** Versions
 - ngx-mat-timepicker version 12.1.0
 - @angular/core version 12.2.15
 - @angular/material version 12.2.13
 - typescript version 4.2.4

**Additional context (optional)**
The source is empty.
![Screen Shot 2022-04-27 at 12 28 41](https://user-images.githubusercontent.com/8827278/165440873-4f9abeb6-1621-4275-b3b8-3cc8952a5cdb.png)

**Comment by tonysamperi** [comment] 2022-05-01 11:06
Hi @SkyTien ,
I can't seem to reproduce this issue...
Could you be more specific about MacOS version and most importantly Chrome version?
Thanks

**Comment by SkyTien** [comment] 2022-05-04 02:12
Hi @tonysamperi ,

I can't reproduce it on your page as well.
But it still happens on my page.
And it also happens on Firefox.
![Screen Shot 2022-05-04 at 09 56 17](https://user-images.githubusercontent.com/8827278/166613887-bb9aa43e-67f7-426a-aaf7-d885fe211f96.png)

** Versions

ngx-mat-timepicker version 12.1.0
@angular/core version 12.2.15
@angular/material version 12.2.13
@angular/material-luxon-adapter 12.2.13  
luxon 2.3.0
typescript version 4.2.4

Chrome 
Version 100.0.4896.127 (Official Build) (x86_64)

Name 	Firefox
Version 	100.0
Build ID 	20220428192727

Mac monterey 12.3.1 (21E258)

Please let me know if you need more detail.
Thanks a lot.

**Comment by tonysamperi** [comment] 2022-05-25 19:14
Closing this as the bug can't be reproduced.
If you manage to recreate the bug in a stackblitz environment, feel free to post the issue to stackoverflow since it's for sure something wrong with your code. 

Cheers.

**Comment by arkasya96** [comment] 2023-09-14 07:27
It seems to still be an issue on the official timepicker demo page, but it happens most of the times when you first select a time in the min max validation, then open up other timepickers to select the time, and the clock dialog gets a previous value.

**Comment by tonysamperi** [comment] 2023-09-14 18:09
@arkasya96 I just clicked all the timepickers after setting different times in each one.
I get the correct values.

**Comment by arkasya96** [comment] 2023-09-14 18:32
So I read in all the issues, that you get the correct values. Well, start by not clicking all of them. The issue starts with min - max validation -> select a time -> open Append to input example -> when you select another time here, the value in the input field jumps to the Open programmatically example. I just reproduced it like 10 times. It happens in chrome. If you tried it in another browser, please do tell. 
I can describe it a bit more as well, because what I am working on requires many timepicker instances in a single component, and I need quite a few minimum and maximum validations. I took your code from the demo project to set it up, it behaves the same as your page on both Chrome and Edge. 



![timepicker-fault](https://github.com/tonysamperi/ngx-mat-timepicker/assets/28351001/39670dcf-b81e-486d-a871-d08297b0ce17)

**Comment by tonysamperi** [comment] 2023-09-14 18:41
@arkasya96 ok now I reproduced the issue. Let's say that the page is not exactly the best playground, since all the pickers use the same ngModel.
Anyway the issue is caused by the original architecture (which is not of my making) which uses one single instance of the TimePickerService for all the dialogs.
So...Good for multiple pickers? I'd say no. Memory saving? Maybe.
I'll dig this to see if I can find a workaround!

**Comment by arkasya96** [comment] 2023-09-14 18:43
Thank you so much! I really appreciate this.

**Comment by tonysamperi** [comment] 2023-10-21 19:49
@arkasya96 ok I figured it out! Releasing in a few moments on v16 for now.

**Closed** 2023-10-21 20:45 UTC
Labels: bug
