### ISSUE TITLE
ngx-mat-timepicker shows "invalidDateTime" in Brave Browser but works fine in Chrome and Edge

### ISSUE THREAD

**Issue by LuigiWoodhouse** [tonysamperi/ngx-mat-timepicker#52] opened 2023-02-09 03:30 UTC
Whenever I try to use ngx-time-picker package, the user will click the input box and a menu will pop up where they can select the time. However after selecting the time "Invalid DateTime". This only happens with Brave Browser. However , whenever I try it on Google Chrome or Microsoft Edge, the ngx-time-picker works just fine as the time selected by the user from the popup menu is the time displayed in the input box. What might be causing this?

https://stackoverflow.com/questions/75393607/ngx-mat-timepicker-shows-invaliddatetime-in-brave-browser-but-works-fine-in-ch

**Comment by ashishpCACTUS** [comment] 2023-02-09 08:21
The issue has not surfaced with Chrome also with the move to chromium 110.0.5481.77/78. Currently edge is on 109 version thus it works on Edge. Please suggest any workaround / fix for Chrome and Brave.

**Comment by tonysamperi** [comment] 2023-02-09 18:45
Ok, I'm closing this as duplicate of #51

**Closed by tonysamperi** 2023-02-09 18:45 UTC
